name: 'Hasura Change Summary'
description: 'Generate readable Hasura metadata change summaries'
author: 'Fieldguide'
inputs:
  github_token:
    required: true
    description: 'GITHUB_TOKEN secret'
  project_dir:
    required: false
    description: 'Hasura project directory, relative to GITHUB_WORKSPACE'
    default: '.'
outputs:
  change:
    description: 'Structured change JSON'
  change_markdown:
    description: 'Markdown change summary'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: message-circle
  color: gray-dark
