name: 'Hasura Change Summary'
description: 'Generate readable Hasura metadata change summaries'
author: 'Fieldguide'
inputs:
  github_token:
    required: true
    description: 'GITHUB_TOKEN secret'
  project_dir:
    required: false
    description: 'Hasura project directory, relative to GITHUB_WORKSPACE'
    default: '.'
  hasura_endpoint:
    required: false
    description: 'Hasura GraphQL engine http(s) endpoint, used for deep console links'
outputs:
  change_html:
    description: 'HTML change summary'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: message-circle
  color: gray-dark
