name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install
      - run: npm run all
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build project
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ['v2', 'v3']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_dir: '__tests__/fixtures/${{ matrix.config }}'
